In [1]:
import pandas as pd
import numpy as np

In [345]:
df = pd.read_csv('파일럿PJ_분석매장반영_2차.csv',index_col=0, encoding='utf-8-sig')

/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/2514982363.py:1: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('파일럿PJ_분석매장반영_2차.csv',index_col=0, encoding='utf-8-sig')

In [346]:
df.isna().sum()

매장코드                 0
매장명                  0
스타일코드                0
스타일명                 0
최초입고일                0
최종입고일                0
최초출고일                0
최종출고일                0
현판가                  0
예판가                  0
결판가                  0
단품코드                 0
누적매장순수입고량           11
누적입고량               11
누적출고량           451981
누적판매량           339018
기간판매량           441202
잔여재고량                0
누적판매율[입고량대비]    339018
기간판매율[입고량대비]    441202
기간입고량           428118
기간출고량           453537
Date                 0
dtype: int64

In [319]:
df = df.fillna(0)

In [300]:
df.head()

,매장코드,매장명,스타일코드,스타일명,최초입고일,최종입고일,최초출고일,최종출고일,현판가,예판가,결판가,단품코드,누적매장순수입고량,누적입고량,누적출고량,누적판매량,기간판매량,잔여재고량,누적판매율[입고량대비],기간판매율[입고량대비],기간입고량,기간출고량,Date
0,A8LH,NC일산,SPKWE11W07,[소프트얀] 하찌 반집업 니트,2023-11-16,2023-12-20,2023-11-17,2023-12-26,49900,49900,49900,SPKWE11W0759085,3.0,3.0,0.0,0.0,0.0,3,0,0,3.0,0.0,231117
1,A8LH,NC일산,SPKWE11W07,[소프트얀] 하찌 반집업 니트,2023-11-16,2023-12-20,2023-11-17,2023-12-26,49900,49900,49900,SPKWE11W0759090,2.0,2.0,0.0,0.0,0.0,2,0,0,2.0,0.0,231117
2,A8LH,NC일산,SPKWE11W07,[소프트얀] 하찌 반집업 니트,2023-11-16,2023-12-20,2023-11-17,2023-12-26,49900,49900,49900,SPKWE11W0759095,2.0,2.0,0.0,0.0,0.0,2,0,0,2.0,0.0,231117
3,A8LJ,NC고잔,SPKWE11W07,[소프트얀] 하찌 반집업 니트,2023-11-16,2023-12-20,2023-11-17,2023-12-26,49900,49900,49900,SPKWE11W0759085,3.0,3.0,0.0,0.0,0.0,3,0,0,3.0,0.0,231117
4,A8LJ,NC고잔,SPKWE11W07,[소프트얀] 하찌 반집업 니트,2023-11-16,2023-12-20,2023-11-17,2023-12-26,49900,49900,49900,SPKWE11W0759090,2.0,2.0,0.0,0.0,0.0,2,0,0,2.0,0.0,231117

In [301]:
df.isnull().sum()

매장코드            0
매장명             0
스타일코드           0
스타일명            0
최초입고일           0
최종입고일           0
최초출고일           0
최종출고일           0
현판가             0
예판가             0
결판가             0
단품코드            0
누적매장순수입고량       0
누적입고량           0
누적출고량           0
누적판매량           0
기간판매량           0
잔여재고량           0
누적판매율[입고량대비]    0
기간판매율[입고량대비]    0
기간입고량           0
기간출고량           0
Date            0
dtype: int64

# 1.결품률

In [302]:
def cal_minus(x):
    minus = len(df[(df['스타일코드'] == x) & (df['잔여재고량'] <= 0)]) / len(df[df['스타일코드'] == x]) * 100
    name = df[df['스타일코드']== x]['스타일명'].unique()
    period = df[df['스타일코드'] == x]['Date'].iloc[0]
    return x, name, period, minus

In [303]:
codes = []
minuses = []
names = []
periods = []
for x in df['스타일코드'].unique():
    minus = len(df[(df['스타일코드'] == x) & (df['잔여재고량'] <= 0)]) / len(df[df['스타일코드'] == x]) * 100
    name = df[df['스타일코드']== x]['스타일명'].unique()
    period = df[df['스타일코드'] == x]['Date'].iloc[0]
    codes.append(x)
    minuses.append(minus)
    names.append(name)
    periods.append(period)

In [304]:
df_minus = pd.DataFrame({'스타일코드':codes, '스타일명':names, '판매시작일':periods, '결품률':minuses})
#df_minus.to_csv('기업공유_결품률.csv', encoding='utf-8-sig')
df_minus

         스타일코드                        스타일명   판매시작일        결품률
0   SPKWE11W07          [[소프트얀] 하찌 반집업 니트]  231117   3.088688
1   SPCKE12W02       [[소프트얀] 라운드넥 케이블 가디건]  231129   0.031153
2   SPKWE12W01       [[소프트얀] 라운드넥 케이블 풀오버]  231129   0.038089
3   SPTAE11W05     [[데일리지] 웜 풀밴딩 스트레치 와이드]  231206  15.691346
4   SPTAE11W06     [[데일리지] 웜 풀밴딩 스트레치 부츠컷]  231206  17.650876
5   SPCKE11W08      [[소프트얀] 소프트 하찌 집업 가디건]  231207   0.000000
6   SPCKE23W02           [[소프트얀] 라운드넥 가디건]  231219   0.128261
7   SPTAEA9M01             [[에센셜] 와이드 슬랙스]  231220   0.455274
8   SPTAE23M05         [[에센셜] 벨티드 와이드 슬랙스]  231220   1.023454
9   SPCKE11W99                 [[날개사] 가디건]  231220   0.278649
10  SPTAEA9W01           [[에센셜] 스트레이트 슬랙스]  231221   0.019007
11  SPTAE23M03  [[에센셜] 크롭 테이퍼드 슬랙스 (-5CM)]  231221   0.117302
12  SPTAE23M04        [[에센셜] 풀밴딩 테이퍼드 슬랙스]  231221   0.016292
13  SPTAE23W03           [[에센셜] 롱 와이드 슬랙스]  231221   0.527744
14  SPTAE23W04   [[에센셜] 크롭 와이드 슬랙스 (-5CM)]  231221   0.349384
15  SPTAEA9M02          [[에센셜] 롱 테이퍼드 슬랙스]  231221   0.330797
16  SPKWE12W99                 [[날개사] 스웨터]  240104   0.000000
17  SPCKE11W98                 [배색 집업 가디건]  240105   0.000000
18  SPTAE23M07          [[에센셜] 원턱 와이드 슬랙스]  240108   0.085589
19  SPKWE23W06       [[소프트얀] 스트라이프 반오픈 니트]  240109   0.000000
20  SPLWE23M12          [[밀라노조직] 라운드넥 긴팔티]  240110   0.111045
21  SPCKE12W94             [[날개사] 볼레로 가디건]  240110   0.000000
22  SPCKE12W93                [빅카라 집업 가디건]  240112   0.000000
23  SPCKE12W03      [[소프트얀] 밀라노 조직 V넥 가디건]  240112   0.000000
24  SPKWE11W95        [[울블렌드] V넥 카라 케이블니트]  240119   0.396825

# 2.매장간편차

In [305]:
df['기간판매율[입고량대비]'] = pd.to_numeric(df['기간판매율[입고량대비]'], errors='coerce').astype(float)
df['누적판매율[입고량대비]'] = pd.to_numeric(df['누적판매율[입고량대비]'], errors='coerce').astype(float)

In [307]:
df_mean = df.groupby(['매장코드', '매장명', '스타일코드', 'Date'])[['기간판매율[입고량대비]', '누적판매율[입고량대비]']].mean()
df_mean2 = df_mean.groupby(['스타일코드', 'Date'])['기간판매율[입고량대비]'].std()
df_mean3 = df_mean2.groupby('스타일코드').mean()

In [308]:
df_mean3 = pd.DataFrame(df_mean3).reset_index()
df_mean3

         스타일코드  기간판매율[입고량대비]
0   SPCKE11W08      1.365102
1   SPCKE11W98      1.094824
2   SPCKE11W99      1.400940
3   SPCKE12W02      0.973106
4   SPCKE12W03      1.051840
5   SPCKE12W93      1.638096
6   SPCKE12W94      0.904639
7   SPCKE23W02      1.279746
8   SPKWE11W07      2.586871
9   SPKWE11W95      2.653434
10  SPKWE12W01      1.248061
11  SPKWE12W99      1.324018
12  SPKWE23W06      0.863196
13  SPLWE23M12      1.363914
14  SPTAE11W05      3.635238
15  SPTAE11W06      4.071607
16  SPTAE23M03      0.848835
17  SPTAE23M04      0.764786
18  SPTAE23M05      1.313381
19  SPTAE23M07      0.741125
20  SPTAE23W03      0.999035
21  SPTAE23W04      1.109896
22  SPTAEA9M01      1.029964
23  SPTAEA9M02      0.864123
24  SPTAEA9W01      0.667453

In [309]:
df_final = pd.merge(df_minus, df_mean3, on='스타일코드')

In [310]:
df_final

         스타일코드                        스타일명   판매시작일        결품률  기간판매율[입고량대비]
0   SPKWE11W07          [[소프트얀] 하찌 반집업 니트]  231117   3.088688      2.586871
1   SPCKE12W02       [[소프트얀] 라운드넥 케이블 가디건]  231129   0.031153      0.973106
2   SPKWE12W01       [[소프트얀] 라운드넥 케이블 풀오버]  231129   0.038089      1.248061
3   SPTAE11W05     [[데일리지] 웜 풀밴딩 스트레치 와이드]  231206  15.691346      3.635238
4   SPTAE11W06     [[데일리지] 웜 풀밴딩 스트레치 부츠컷]  231206  17.650876      4.071607
5   SPCKE11W08      [[소프트얀] 소프트 하찌 집업 가디건]  231207   0.000000      1.365102
6   SPCKE23W02           [[소프트얀] 라운드넥 가디건]  231219   0.128261      1.279746
7   SPTAEA9M01             [[에센셜] 와이드 슬랙스]  231220   0.455274      1.029964
8   SPTAE23M05         [[에센셜] 벨티드 와이드 슬랙스]  231220   1.023454      1.313381
9   SPCKE11W99                 [[날개사] 가디건]  231220   0.278649      1.400940
10  SPTAEA9W01           [[에센셜] 스트레이트 슬랙스]  231221   0.019007      0.667453
11  SPTAE23M03  [[에센셜] 크롭 테이퍼드 슬랙스 (-5CM)]  231221   0.117302      0.848835
12  SPTAE23M04        [[에센셜] 풀밴딩 테이퍼드 슬랙스]  231221   0.016292      0.764786
13  SPTAE23W03           [[에센셜] 롱 와이드 슬랙스]  231221   0.527744      0.999035
14  SPTAE23W04   [[에센셜] 크롭 와이드 슬랙스 (-5CM)]  231221   0.349384      1.109896
15  SPTAEA9M02          [[에센셜] 롱 테이퍼드 슬랙스]  231221   0.330797      0.864123
16  SPKWE12W99                 [[날개사] 스웨터]  240104   0.000000      1.324018
17  SPCKE11W98                 [배색 집업 가디건]  240105   0.000000      1.094824
18  SPTAE23M07          [[에센셜] 원턱 와이드 슬랙스]  240108   0.085589      0.741125
19  SPKWE23W06       [[소프트얀] 스트라이프 반오픈 니트]  240109   0.000000      0.863196
20  SPLWE23M12          [[밀라노조직] 라운드넥 긴팔티]  240110   0.111045      1.363914
21  SPCKE12W94             [[날개사] 볼레로 가디건]  240110   0.000000      0.904639
22  SPCKE12W93                [빅카라 집업 가디건]  240112   0.000000      1.638096
23  SPCKE12W03      [[소프트얀] 밀라노 조직 V넥 가디건]  240112   0.000000      1.051840
24  SPKWE11W95        [[울블렌드] V넥 카라 케이블니트]  240119   0.396825      2.653434

In [312]:
df_final.columns = ['스타일코드', '스타일명', '판매시작일', '결품률', '매장간 소진율 편차']

In [313]:
df_final['아이템'] = df_final['스타일코드'].str[2:4]

In [314]:
df_final['복종'] = df_final['스타일코드'].str[7]

In [315]:
df_final.to_excel('기업공유_결품률소진율_소진율결측치0으로.xlsx')

# 3.분배등급별

In [267]:
table = pd.read_excel('1231 분배등급.xlsx')

In [321]:
df.isna().sum()

매장코드            0
매장명             0
스타일코드           0
스타일명            0
최초입고일           0
최종입고일           0
최초출고일           0
최종출고일           0
현판가             0
예판가             0
결판가             0
단품코드            0
누적매장순수입고량       0
누적입고량           0
누적출고량           0
누적판매량           0
기간판매량           0
잔여재고량           0
누적판매율[입고량대비]    0
기간판매율[입고량대비]    0
기간입고량           0
기간출고량           0
Date            0
dtype: int64

In [325]:
df['기간판매율[입고량대비]'] = pd.to_numeric(df['기간판매율[입고량대비]'], errors='coerce').astype(float)
df['누적판매율[입고량대비]'] = pd.to_numeric(df['누적판매율[입고량대비]'], errors='coerce').astype(float)

In [328]:
df2 = df[df['스타일코드'] != 'SPTAE11W05']
df2 = df2[df2['스타일코드'] != 'SPTAE11W06']

In [338]:
def get_pj_result(df, table, grade):
        
        forman_a = table[table['포맨'] == grade]['매장코드'].unique()
        df = df[df['기간판매율[입고량대비]'] > 0]
        df_forman_a = df[df['매장코드'].isin(forman_a)]
        df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
        df_forman_a2 = df_forman_a[df_forman_a['아이템'] == 'TA']
        df_forman_a3 = df_forman_a2[df_forman_a2['스타일코드'] != 'SPTAE23M07']

        codes = []
        minuses = []
        names = []
        periods = []
        for x in df_forman_a3['스타일코드'].unique():
            a = len(df_forman_a3[(df_forman_a3['스타일코드'] == x) & (df_forman_a3['잔여재고량'] <= 0)])
            b = len(df_forman_a3[df_forman_a3['스타일코드'] == x])
            minus = ( (a/b)  * 100 )
            name = df_forman_a3[df_forman_a3['스타일코드']== x]['스타일명'].unique()
            period = df_forman_a3[df_forman_a3['스타일코드'] == x]['Date'].iloc[0]
            codes.append(x)
            minuses.append(minus)
            names.append(name)
            periods.append(period)

        df_minus_a = pd.DataFrame({'스타일코드':codes, '스타일명':names, '판매시작일':periods, '결품률':minuses})

        # df_early = df_forman_a3[(df_forman_a3['스타일코드'] == 'SPTAE11W05') 
        #                         | (df_forman_a3['스타일코드'] == 'SPTAE11W06')]
        # df_early2 = df_early[df_early['Date'] <= 240106]
        # df_mean_early = df_early2.groupby(['매장코드', '매장명', '스타일코드', 'Date'])[['기간판매율[입고량대비]', '누적판매율[입고량대비]']].mean()
        # df_mean_early2 = df_mean_early.groupby(['스타일코드', 'Date'])['기간판매율[입고량대비]'].std()
        # df_mean_early3 = df_mean_early2.groupby('스타일코드').mean()
        # df_mean_early3 = pd.DataFrame(df_mean_early3).reset_index()
        # df_mean_early3['복종'] = df_mean_early3['스타일코드'].str[7]

        # df_forman_a3 = df_forman_a3[df_forman_a3['스타일코드'] != 'SPTAE11W05']
        # df_forman_a3 = df_forman_a3[df_forman_a3['스타일코드'] != 'SPTAE11W06']
        df_mean_a = df_forman_a3.groupby(['매장코드', '매장명', '스타일코드', 'Date'])[['기간판매율[입고량대비]', '누적판매율[입고량대비]']].mean()
        df_mean2_a = df_mean_a.groupby(['스타일코드', 'Date'])['기간판매율[입고량대비]'].std()
        df_mean3_a = df_mean2_a.groupby('스타일코드').mean()
        df_mean3_a = pd.DataFrame(df_mean3_a).reset_index()
        df_mean3_a['복종'] = df_mean3_a['스타일코드'].str[7]

        # df_mean3_a = pd.concat([df_mean3_a, df_mean_early3], axis=0)

        df_final_a = pd.merge(df_minus_a, df_mean3_a, on='스타일코드')
        df_final_a.columns = ['스타일코드', '스타일명', '판매시작일', '결품률','매장간 소진율 편차', '복종']

        pj_code = ['SPTAEA9W01', 'SPTAE23M03', 'SPTAE23M04']

        pj = []
        selected_rows = df_final_a[df_final_a['스타일코드'].isin(pj_code)]
        pj_minus_mean = selected_rows['결품률'].mean()
        pj_sojin_mean = selected_rows['매장간 소진율 편차'].mean()
        pj.append(pj_minus_mean)
        pj.append(pj_sojin_mean)

        npj = []

        not_selected_rows = df_final_a[~df_final_a['스타일코드'].isin(pj_code)]
        npj_minus_mean = not_selected_rows['결품률'].mean()
        npj_sojin_mean = not_selected_rows['매장간 소진율 편차'].mean()
        npj.append(npj_minus_mean)
        npj.append(npj_sojin_mean)

        

        return pd.DataFrame({'파일럿 적용':pj, '파일럿 미적용': npj})

In [339]:
for i in ['A', 'B', 'C', 'D', 'E', 'F']:
    df_result = get_pj_result(df2, table, i)
    print(df_result)
    df_result.to_excel(f'{i}등급의 결품률 및 소진율 편차_결측치0으로.xlsx')

     파일럿 적용   파일럿 미적용
0  0.000000  1.344186
1  4.706956  4.880737
     파일럿 적용    파일럿 미적용
0  0.000000   6.436431
1  4.804091  10.043362
      파일럿 적용   파일럿 미적용
0   1.191957  10.20840
1  10.349421   9.68137
      파일럿 적용    파일럿 미적용
0   1.204819  10.262162
1  12.752010   6.074684
      파일럿 적용   파일럿 미적용
0   2.150538  9.314904
1  12.194515  7.772873
    파일럿 적용   파일럿 미적용
0  0.00000  7.249371
1  7.68311  7.907611

/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/3209814471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/3209814471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/3209814471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/3209814471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/3209814471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/3209814471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]

In [337]:
for i in ['A', 'B', 'C', 'D', 'E', 'F']:
    df_result = get_pj_result(df2, table, i)
    print(df_result)
    #df_result.to_excel(f'{i}등급의 결품률 및 소진율 편차_결측치0으로.xlsx')

     파일럿 적용   파일럿 미적용
0  0.000000  1.344186
1  4.706956  4.880737
     파일럿 적용    파일럿 미적용
0  0.000000   6.436431
1  4.804091  10.043362
      파일럿 적용   파일럿 미적용
0   1.191957  10.20840
1  10.349421   9.68137
      파일럿 적용    파일럿 미적용
0   1.204819  10.262162
1  12.752010   6.074684
      파일럿 적용   파일럿 미적용
0   2.150538  9.314904
1  12.194515  7.772873
    파일럿 적용   파일럿 미적용
0  0.00000  7.249371
1  7.68311  7.907611

/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/3209814471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/3209814471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/3209814471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/3209814471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/3209814471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/3209814471.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]

In [340]:
df_a = pd.read_excel('A등급의 결품률 및 소진율 편차_결측치0으로.xlsx', index_col=0)
df_b = pd.read_excel('B등급의 결품률 및 소진율 편차_결측치0으로.xlsx', index_col=0)
df_c = pd.read_excel('C등급의 결품률 및 소진율 편차_결측치0으로.xlsx', index_col=0)
df_d = pd.read_excel('D등급의 결품률 및 소진율 편차_결측치0으로.xlsx', index_col=0)
df_e = pd.read_excel('E등급의 결품률 및 소진율 편차_결측치0으로.xlsx', index_col=0)
df_f = pd.read_excel('F등급의 결품률 및 소진율 편차_결측치0으로.xlsx', index_col=0)

In [341]:
df_a['등급'] = 'A'
df_b['등급'] = 'B'
df_c['등급'] = 'C'
df_d['등급'] = 'D'
df_e['등급'] = 'E'
df_f['등급'] = 'F'

In [342]:
df_grade = pd.concat([df_a, df_b, df_c, df_d, df_e, df_f])

In [343]:
df_grade

      파일럿 적용    파일럿 미적용 등급
0   0.000000   1.344186  A
1   4.706956   4.880737  A
0   0.000000   6.436431  B
1   4.804091  10.043362  B
0   1.191957  10.208400  C
1  10.349421   9.681370  C
0   1.204819  10.262162  D
1  12.752010   6.074684  D
0   2.150538   9.314904  E
1  12.194515   7.772873  E
0   0.000000   7.249371  F
1   7.683110   7.907611  F

In [344]:
df_grade.to_excel('분배별 결품률 및 소진율 편차_결측치0으로.xlsx')

In [165]:
forman_a = table[table['포맨'] == 'A']['매장코드'].unique()
df_forman_a = df[df['매장코드'].isin(forman_a)]
df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
df_forman_a2 = df_forman_a[df_forman_a['아이템'] == 'TA']
df_forman_a3 = df_forman_a2[df_forman_a2['스타일코드'] != 'SPTAE23M07']

df_0120 = df_forman_a3[df_forman_a3['Date'] == 240120]
df_0120_mean = df_0120.groupby(['매장코드', '매장명', '스타일코드', 'Date'])[['기간판매율[입고량대비]', '누적판매율[입고량대비]']].mean()
df_0120_mean2 = df_0120_mean.groupby(['스타일코드', 'Date'])['누적판매율[입고량대비]'].std()
df_0120_mean3 = df_0120_mean2.groupby('스타일코드').mean()
df_0120_mean3

/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/746195592.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]

스타일코드
SPTAE11W05    19.778673
SPTAE11W06    21.999945
SPTAE23M03     6.408440
SPTAE23M04     6.379498
SPTAE23M05     7.361314
SPTAE23W03     5.413873
SPTAE23W04     3.108824
SPTAEA9M01     5.990417
SPTAEA9M02     3.232774
SPTAEA9W01     2.939751
Name: 누적판매율[입고량대비], dtype: float64

In [288]:
df = df[df['기간판매율[입고량대비]'] > 0]
forman_a = table[table['포맨'] == 'A']['매장코드'].unique()
df_forman_a = df[df['매장코드'].isin(forman_a)]
df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
df_forman_a2 = df_forman_a[df_forman_a['아이템'] == 'TA']
df_forman_a3 = df_forman_a2[df_forman_a2['스타일코드'] != 'SPTAE23M07']

df_mean_a = df_forman_a3.groupby(['매장코드', '매장명', '스타일코드', 'Date'])[['기간판매율[입고량대비]', '누적판매율[입고량대비]']].mean()
df_mean_a2 = df_mean_a.groupby(['스타일코드', 'Date'])['기간판매율[입고량대비]'].mean()
df_mean_a2

/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/1071977497.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]

스타일코드       Date
SPTAE11W05  231207     9.375000
            231208    11.111111
            231209     6.481481
            231210     6.944444
            231211    10.763889
                        ...
SPTAEA9W01  240116     6.696429
            240117     4.599567
            240118     4.653680
            240119     4.782609
            240120     7.118559
Name: 기간판매율[입고량대비], Length: 301, dtype: float64

In [284]:
def get_grade_sojin(df, table, grade):
    df = df[df['기간판매율[입고량대비]'] > 0]
    forman_a = table[table['포맨'] == grade]['매장코드'].unique()
    df_forman_a = df[df['매장코드'].isin(forman_a)]
    df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
    df_forman_a2 = df_forman_a[df_forman_a['아이템'] == 'TA']
    df_forman_a3 = df_forman_a2[df_forman_a2['스타일코드'] != 'SPTAE23M07']

    df_mean_a = df_forman_a3.groupby(['매장코드', '매장명', '스타일코드', 'Date'])[['기간판매율[입고량대비]', '누적판매율[입고량대비]']].mean()
    df_mean_a2 = df_mean_a.groupby(['스타일코드', 'Date'])['기간판매율[입고량대비]'].mean()
    df_mean_a2 = pd.DataFrame(df_mean_a2)
    df_mean_a2 = df_mean_a2.reset_index()
    df_mean_a2.columns = ['스타일코드', 'Date', f'{grade}등급매장의 평균소진율']

    return df_mean_a2

In [285]:
grade_a = get_grade_sojin(df, table, 'A')
grade_b = get_grade_sojin(df, table, 'B')
grade_c = get_grade_sojin(df, table, 'C')
grade_d = get_grade_sojin(df, table, 'D')
grade_e = get_grade_sojin(df, table, 'E')
grade_f = get_grade_sojin(df, table, 'F')

/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/600500863.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/600500863.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/600500863.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/600500863.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/600500863.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]
/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_82185/600500863.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_forman_a['아이템'] = df_forman_a['스타일코드'].str[2:4]

In [289]:
grade_df = pd.merge(grade_a, grade_b, on=['스타일코드', 'Date'], how='outer')
grade_df = pd.merge(grade_df, grade_c, on=['스타일코드', 'Date'], how='outer')
grade_df = pd.merge(grade_df, grade_d, on=['스타일코드', 'Date'], how='outer')
grade_df = pd.merge(grade_df, grade_e, on=['스타일코드', 'Date'], how='outer')
grade_df = pd.merge(grade_df, grade_f, on=['스타일코드', 'Date'], how='outer')
grade_df

,스타일코드,Date,A등급매장의 평균소진율,B등급매장의 평균소진율,C등급매장의 평균소진율,D등급매장의 평균소진율,E등급매장의 평균소진율,F등급매장의 평균소진율
0,SPTAE11W05,231207,9.375000,14.444444,33.333333,38.888889,33.333333,NaN
1,SPTAE11W05,231208,11.111111,15.178571,38.888889,44.444444,NaN,NaN
2,SPTAE11W05,231209,6.481481,19.166667,34.490741,42.777778,NaN,NaN
3,SPTAE11W05,231210,6.944444,15.000000,26.041667,44.444444,33.333333,NaN
4,SPTAE11W05,231211,10.763889,18.055556,33.333333,50.000000,NaN,NaN
...,...,...,...,...,...,...,...,...
325,SPTAE23M04,240117,NaN,NaN,18.750000,NaN,NaN,11.111111
326,SPTAE23W04,231222,NaN,NaN,50.000000,NaN,NaN,NaN
327,SPTAE23W04,231224,NaN,NaN,50.000000,NaN,NaN,NaN
328,SPTAE23W04,240112,NaN,NaN,50.000000,50.000000,50.000000,50.000000
329,SPTAE23M04,231223,NaN,NaN,NaN,50.000000,25.000000,5.555556

In [290]:
grade_df['편차'] = grade_df.iloc[:, 2:].std(axis=1)

grade_df

,스타일코드,Date,A등급매장의 평균소진율,B등급매장의 평균소진율,C등급매장의 평균소진율,D등급매장의 평균소진율,E등급매장의 평균소진율,F등급매장의 평균소진율,편차
0,SPTAE11W05,231207,9.375000,14.444444,33.333333,38.888889,33.333333,NaN,13.072130
1,SPTAE11W05,231208,11.111111,15.178571,38.888889,44.444444,NaN,NaN,16.705276
2,SPTAE11W05,231209,6.481481,19.166667,34.490741,42.777778,NaN,NaN,16.134436
3,SPTAE11W05,231210,6.944444,15.000000,26.041667,44.444444,33.333333,NaN,14.785993
4,SPTAE11W05,231211,10.763889,18.055556,33.333333,50.000000,NaN,NaN,17.401285
...,...,...,...,...,...,...,...,...,...
325,SPTAE23M04,240117,NaN,NaN,18.750000,NaN,NaN,11.111111,5.401510
326,SPTAE23W04,231222,NaN,NaN,50.000000,NaN,NaN,NaN,NaN
327,SPTAE23W04,231224,NaN,NaN,50.000000,NaN,NaN,NaN,NaN
328,SPTAE23W04,240112,NaN,NaN,50.000000,50.000000,50.000000,50.000000,0.000000
329,SPTAE23M04,231223,NaN,NaN,NaN,50.000000,25.000000,5.555556,22.280017

In [293]:
grade_df_std = grade_df.groupby('스타일코드')['편차'].mean()
grade_df_std.to_excel('등급 간 소진율 편차.xlsx')

In [295]:
grade_df_mean = grade_df.groupby('스타일코드').mean()
grade_df_mean

,Date,A등급매장의 평균소진율,B등급매장의 평균소진율,C등급매장의 평균소진율,D등급매장의 평균소진율,E등급매장의 평균소진율,F등급매장의 평균소진율,편차
스타일코드,,,,,,,,
SPTAE11W05,235170.777778,8.268251,12.431327,27.230622,32.738214,36.726190,NaN,11.897788
SPTAE11W06,235170.777778,10.122135,16.420386,29.197121,32.492623,36.590909,NaN,11.803740
SPTAE23M03,237149.166667,10.318527,14.841876,19.220377,20.657327,24.021885,12.561144,10.926186
SPTAE23M04,237149.166667,7.973456,10.400559,20.058937,18.057144,23.994709,15.182246,8.536258
SPTAE23M05,236957.935484,16.639194,29.412616,39.602920,NaN,NaN,NaN,13.215868
SPTAE23W03,237353.551724,20.364284,36.708829,46.207265,49.305556,47.727273,48.611111,13.912516
SPTAE23W04,237149.166667,23.410714,35.133333,48.250000,50.000000,50.000000,50.000000,10.961444
SPTAEA9M01,236957.935484,14.030358,18.020172,25.092921,32.870441,30.443437,28.355899,10.577845
SPTAEA9M02,237149.166667,14.596946,22.253212,29.715089,28.696095,39.719888,25.356198,11.294950
SPTAEA9W01,237353.551724,8.439575,12.235914,17.621323,30.354167,42.569444,20.501867,12.765958