In [1]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv('22년매장재고_수정.csv')

/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_17009/2602859300.py:1: DtypeWarning: Columns (16,17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('22년매장재고_수정.csv')

In [30]:
list = ['기간판매량','잔여재고량', '누적판매율[입고량대비]', '기간판매율[입고량대비]']
for i in list:
    # '기간판매량' 열을 float으로 변환하고, 'NaN' 값을 null로 처리합니다.
    df[i] = pd.to_numeric(df[i], errors='coerce')

    # 'NaN' 값을 null로 처리하려면 np.nan을 사용합니다.
    df[i].replace('NaN', np.nan, inplace=True)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8547968 entries, 0 to 8547967
Data columns (total 24 columns):
 #   Column        Dtype
---  ------        -----
 0   Year          int64
 1   Week          int64
 2   매장코드          object
 3   매장명           object
 4   복종            object
 5   스타일코드         object
 6   스타일명          object
 7   최초입고일         object
 8   최종입고일         object
 9   최초출고일         object
 10  최종출고일         object
 11  결판가           int64
 12  누적매장순수입고량     float64
 13  누적입고량         float64
 14  누적출고량         float64
 15  누적판매량         float64
 16  기간판매량         float64
 17  잔여재고량         float64
 18  누적판매율[입고량대비]  float64
 19  기간판매율[입고량대비]  float64
 20  기간입고량         float64
 21  기간출고량         float64
 22  소진율           float64
 23  기간판매량float    float64
dtypes: float64(12), int64(3), object(9)
memory usage: 1.5+ GB

In [14]:
df.head()

,Year,Week,매장코드,매장명,복종,스타일코드,스타일명,최초입고일,최종입고일,최초출고일,...,누적입고량,누적출고량,누적판매량,기간판매량,잔여재고량,누적판매율[입고량대비],기간판매율[입고량대비],기간입고량,기간출고량,소진율
0,2022,1,A8LC,2001중계,A,SPABBA8A01,남성 스퀘어 사피아노 벨트,2020-12-12,2021-09-27,2021-01-11,...,15.0,NaN,15.0,NaN,0,100,NaN,NaN,NaN,1.000000
1,2022,1,A8LC,2001중계,A,SPACBA8A01,[우디컬렉션] 자수 볼캡,2021-10-06,2021-10-06,2021-10-12,...,27.0,-18.0,9.0,NaN,0,100,NaN,NaN,NaN,0.333333
2,2022,1,A8LC,2001중계,A,SPACCA9A03,(우디) 자수 볼캡,2021-12-15,2023-03-22,2021-12-20,...,36.0,NaN,1.0,NaN,35,2.77777777777778,NaN,NaN,NaN,0.027778
3,2022,1,A8LC,2001중계,A,SPAKB22A01,[SPAO X 맥포스] 슈퍼 팔콘,2020-11-02,2020-11-02,2020-11-03,...,20.0,-16.0,4.0,NaN,0,100,NaN,NaN,NaN,0.200000
4,2022,1,A8LC,2001중계,A,SPAKB22A04,[SPAO X 맥포스] M1 파우치 백,2020-11-02,2020-11-02,2020-11-03,...,16.0,NaN,14.0,NaN,2,87.5,NaN,NaN,NaN,0.875000

In [4]:
df.columns

Index(['Year', 'Week', '매장코드', '매장명', '복종', '스타일코드', '스타일명', '최초입고일', '최종입고일',
       '최초출고일', '최종출고일', '결판가', '누적매장순수입고량', '누적입고량', '누적출고량', '누적판매량',
       '기간판매량', '잔여재고량', '누적판매율[입고량대비]', '기간판매율[입고량대비]', '기간입고량', '기간출고량',
       '소진율'],
      dtype='object')

In [32]:
df_grouped = df.groupby(['Year', 'Week', '매장코드', '매장명']).sum()

/var/folders/x2/c6gjhmqs6h5bl_d26ctv923h0000gn/T/ipykernel_17009/1441759286.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_grouped = df.groupby(['Year', 'Week', '매장코드', '매장명']).sum()

In [33]:
df_grouped.head()

                            결판가  누적매장순수입고량    누적입고량    누적출고량    누적판매량   기간판매량  \
Year Week 매장코드 매장명
2022 1    A8LC 2001중계  25318400    61494.0  73740.0 -12246.0  51006.0   750.0
          A8LH NC일산    42551000    71859.0  89185.0 -17326.0  57014.0   938.0
          A8LJ NC고잔    18126700    46260.0  51831.0  -5571.0  36114.0   575.0
          A8LL NC덕천    19981000    49694.0  60183.0 -10489.0  46842.0   898.0
          A8LM NC송파    44393100    73287.0  86585.0 -13298.0  56925.0  1062.0

                         잔여재고량  누적판매율[입고량대비]  기간판매율[입고량대비]   기간입고량  기간출고량  \
Year Week 매장코드 매장명
2022 1    A8LC 2001중계  10488.0  59347.348269   1103.756906  1262.0   -9.0
          A8LH NC일산    14845.0  83356.743437   1388.104445  1626.0  -20.0
          A8LJ NC고잔    10146.0  41341.138082    571.931249  1085.0    0.0
          A8LL NC덕천     2852.0  53680.350744   1063.704375  1058.0    0.0
          A8LM NC송파    16362.0  94322.976555   1365.381631  1684.0  -47.0

                              소진율  기간판매량float
Year Week 매장코드 매장명
2022 1    A8LC 2001중계  526.197805       750.0
          A8LH NC일산    606.157585       938.0
          A8LJ NC고잔    363.994130       575.0
          A8LL NC덕천    447.270206       898.0
          A8LM NC송파    744.002797      1062.0

In [10]:
df['누적판매량'].isna().sum()

309073

In [34]:
df.head()

,Year,Week,매장코드,매장명,복종,스타일코드,스타일명,최초입고일,최종입고일,최초출고일,...,누적출고량,누적판매량,기간판매량,잔여재고량,누적판매율[입고량대비],기간판매율[입고량대비],기간입고량,기간출고량,소진율,기간판매량float
0,2022,1,A8LC,2001중계,A,SPABBA8A01,남성 스퀘어 사피아노 벨트,2020-12-12,2021-09-27,2021-01-11,...,NaN,15.0,NaN,0.0,100.000000,NaN,NaN,NaN,1.000000,NaN
1,2022,1,A8LC,2001중계,A,SPACBA8A01,[우디컬렉션] 자수 볼캡,2021-10-06,2021-10-06,2021-10-12,...,-18.0,9.0,NaN,0.0,100.000000,NaN,NaN,NaN,0.333333,NaN
2,2022,1,A8LC,2001중계,A,SPACCA9A03,(우디) 자수 볼캡,2021-12-15,2023-03-22,2021-12-20,...,NaN,1.0,NaN,35.0,2.777778,NaN,NaN,NaN,0.027778,NaN
3,2022,1,A8LC,2001중계,A,SPAKB22A01,[SPAO X 맥포스] 슈퍼 팔콘,2020-11-02,2020-11-02,2020-11-03,...,-16.0,4.0,NaN,0.0,100.000000,NaN,NaN,NaN,0.200000,NaN
4,2022,1,A8LC,2001중계,A,SPAKB22A04,[SPAO X 맥포스] M1 파우치 백,2020-11-02,2020-11-02,2020-11-03,...,NaN,14.0,NaN,2.0,87.500000,NaN,NaN,NaN,0.875000,NaN

In [35]:
df['아이템'] = df['스타일코드'].str[2:4]

In [36]:
df.head()

,Year,Week,매장코드,매장명,복종,스타일코드,스타일명,최초입고일,최종입고일,최초출고일,...,누적판매량,기간판매량,잔여재고량,누적판매율[입고량대비],기간판매율[입고량대비],기간입고량,기간출고량,소진율,기간판매량float,아이템
0,2022,1,A8LC,2001중계,A,SPABBA8A01,남성 스퀘어 사피아노 벨트,2020-12-12,2021-09-27,2021-01-11,...,15.0,NaN,0.0,100.000000,NaN,NaN,NaN,1.000000,NaN,AB
1,2022,1,A8LC,2001중계,A,SPACBA8A01,[우디컬렉션] 자수 볼캡,2021-10-06,2021-10-06,2021-10-12,...,9.0,NaN,0.0,100.000000,NaN,NaN,NaN,0.333333,NaN,AC
2,2022,1,A8LC,2001중계,A,SPACCA9A03,(우디) 자수 볼캡,2021-12-15,2023-03-22,2021-12-20,...,1.0,NaN,35.0,2.777778,NaN,NaN,NaN,0.027778,NaN,AC
3,2022,1,A8LC,2001중계,A,SPAKB22A01,[SPAO X 맥포스] 슈퍼 팔콘,2020-11-02,2020-11-02,2020-11-03,...,4.0,NaN,0.0,100.000000,NaN,NaN,NaN,0.200000,NaN,AK
4,2022,1,A8LC,2001중계,A,SPAKB22A04,[SPAO X 맥포스] M1 파우치 백,2020-11-02,2020-11-02,2020-11-03,...,14.0,NaN,2.0,87.500000,NaN,NaN,NaN,0.875000,NaN,AK